### ISSUE TITLE
It can't handle large coverage sets.

### ISSUE THREAD

**Issue by chenghuang-mdsol** [5monkeys/cobertura-action#1]
It will just throw an exception complaining your massage is too large for a comment

**Comment by hannseman** [comment]
Hi, sorry for the late reply. 

One solution for this would be to only show coverage for changed files, like [codecov](https://codecov.io) does reporting on PRs.

Pull requests are welcome!

**Comment by hannseman** [comment]
I just released [v3](https://github.com/5monkeys/cobertura-action/releases/tag/v3) where one can set the option `only_changed_files: true` to only report coverage on files changed in a PR. This should help reducing the amount of lines in the comments. Good luck with your coverage!
