### ISSUE TITLE
Support separate comments for separate reports 

### ISSUE THREAD

**Issue by shaguptashaikh** [5monkeys/cobertura-action#14]
Would be neat to be able to publish separate comments for separate reports, I'm trying to use this for publishing the metrics for two different xml files generated by two different suites, but the same comment is updated for both of them. A new feature would be great where I can pass in a new input for say `report_name` which can be used in the initial comment body as say - title for the report and when you lookup comments for subsequent jobs in `action.js->addComment()`, use the report name to filter instead of the `credits` text? Thanks!

**Comment by hannseman** [comment]
Fixed by #15
