### ISSUE TITLE
Option to show class names instead of file names

### ISSUE THREAD

**Issue by MikeDombo** [5monkeys/cobertura-action#2]
I'd love the option to show class names instead of file names because Java files can contain multiple internal classes. Cobertura has this field available as "name" instead of "filename"

**Comment by hannseman** [comment]
Thanks for your feature request! I've just release v2 of this action which supports showing class names instead of file names by setting `show_class_names: true`. Let me know if there's any issues.

**Comment by MikeDombo** [comment]
Very cool, thanks for putting it in so quickly.
