### ISSUE TITLE
Permission issue on PRs raised from repository forks

### ISSUE THREAD

**Issue by bijujoseph** [5monkeys/cobertura-action#27]
Pull request workflows (event `pull_request`) raised from repository forks get read-only token. This causes the workflows involving `cobertura-action` to fail, due to lack of permission. 
> `Error: Resource not accessible by integration

Actions team recently introduced `pull_request_target`, but that poses additional security risks. To mitigate that, they recommend to split these workflows, a well-written recipe can be found in [2](https://securitylab.github.com/research/github-actions-preventing-pwn-requests)

Certainly, `cobertura-action` accepts `pull_request_number` parameter, but that will put the onus on the workflow author. So, in order to keep things simple, it is better to encapsulate the PR identification logic within this action for workflow_run events. Soon I will be rasing a PR to address this. 

_References_: 
- 1 https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
- 2 https://securitylab.github.com/research/github-actions-preventing-pwn-requests

**Comment by hannseman** [comment]
I think this can be closed now that #28 is merged. I'll update the README to describe splitting up workflows.
