### ISSUE TITLE
Cannot read "line-rate" of undefined

### ISSUE THREAD

**Issue by MikeDombo** [5monkeys/cobertura-action#7]
For whatever reason, one of the elements (not sure what) is missing the line rate. 
Looks like these lines of code should check that the element has that key before accessing it: https://github.com/5monkeys/cobertura-action/blob/master/src/cobertura.js#L53-L54

```
##[error]Cannot read property 'line-rate' of undefined
```

**Comment by hannseman** [comment]
Weird, looks like some of the parsed class-elements ended up as undefined. I've tried to filter them out. Please give `5monkeys/cobertura-action@master ` a try when you have the time. If this solved your issue I'll create a new release. Thanks for your report!

**Comment by MikeDombo** [comment]
Just had the chance to try it out with a pull request which showed the error again, and the fix does work as expected. Thanks!

**Comment by hannseman** [comment]
Thanks for the testing. I just released v5 with a fix:
https://github.com/5monkeys/cobertura-action/releases/tag/v5
