### ISSUE TITLE
Warning in execute

### ISSUE THREAD

**Issue by AntonioLopezSGB** [5monkeys/cobertura-action#79]
The following warning is displayed in the run panel:

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: 5monkeys/cobertura-action@v13. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by flaeppe** [comment]
Closed via #78
