### ISSUE TITLE
Release new version with Node 16 support?

### ISSUE THREAD

**Issue by MikeMatusz** [5monkeys/cobertura-action#84]
#78 was merged, but there hasn't been a new release yet, but all GitHub actions will start running on Node 16 on May 18, which is just a few days aways: https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/

**Comment by MikeMatusz** [comment]
Tagging @hannseman since he created the last release

**Comment by paulz** [comment]
First of all, thank you for the great GitHub action!

We are getting this warning when running this action:

> The node12 is not supported on macOS ARM64 platform. Use node16 instead.

**Comment by flaeppe** [comment]
The new release [v14](https://github.com/5monkeys/cobertura-action/releases/tag/v14) with support for both `node 16` and `node 20` is now available
